version: '3'
services:
  cassandra-db:
    hostname: cassandra-1
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
#    volumes:
#    - ./data/cassandra-1:/var/lib/cassandra:rw
    networks:
    - statepoc
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  seed:
    image: gts-gi-frontend-team-fe-tools-incidents-docker-local.artifactory.swg-devops.com/gts-gi-frontend-incidents-local:1
    links:
    - cassandra-db
    - elasticsearch
    depends_on:
    - cassandra-db
    expose:
    - 1600
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: seed
      CLUSTER_PORT: 1600
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db
    networks:
    - statepoc
    - cinnamon

  cluster:
    image: gts-gi-frontend-team-fe-tools-incidents-docker-local.artifactory.swg-devops.com/gts-gi-frontend-incidents-local:1
    links:
    - seed
    - cassandra-db
    - elasticsearch
    depends_on:
    - seed
    - cassandra-db
    environment:
      JAVA_OPTS: "-Dconfig.resource=cluster-application-docker.conf"
      CLUSTER_IP: cluster
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db
    networks:
    - statepoc
    - cinnamon

  endpoint:
    image: gts-gi-frontend-team-fe-tools-incidents-docker-local.artifactory.swg-devops.com/gts-gi-frontend-incidents-local:1
    environment:
      JAVA_OPTS: "-Dconfig.resource=endpoint-application-docker.conf"
      CLUSTER_IP: endpoint
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
      CASSANDRA_CONTACT_POINT1: cassandra-db
    links:
    - seed
    - cassandra-db
    - elasticsearch
    depends_on:
    - seed
    - cassandra-db
    ports:
    - "8080:8080"
    - "8558:8558"
    - "25520:25520"
    networks:
    - statepoc
    - cinnamon

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 4G
    networks:
      - cinnamon
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    ports:
      - "5601:5601"
    networks:
      - cinnamon
    depends_on:
      - elasticsearch
  backend:
    image: lightbend-docker-registry.bintray.io/cinnamon/cinnamon-vizceral:0.1
    ports:
      - "8999:8999"
    networks:
      - cinnamon
    depends_on:
      - elasticsearch
  web:
    image: lightbend-docker-registry.bintray.io/cinnamon/cinnamon-vizceral-frontend:0.1.1
    ports:
      - "8081:80"
    networks:
      - cinnamon
    depends_on:
      - backend

networks:
  cinnamon:
  statepoc:
    driver: bridge
