apiVersion: v1
kind: Service
metadata:
  labels:
    app: incidents
  name: "incidents-service"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 8558
    protocol: TCP
    targetPort: management
  selector:
    app: "incidents-endpoint"
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incidents-endpoint
  name: incidents-endpoint
  namespace: incidents
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incidents-endpoint
  template:
    metadata:
      labels:
        app: incidents-endpoint
        actorSystemName: incidents
    spec:
      containers:
      - name: incidents
        image: bibilthaysose/incidents
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: management
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /alive
            port: management
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 20
        ports:
        # akka-management and bootstrap
        - name: remoting
          containerPort: 2552
          protocol: TCP
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: JAVA_OPTS
          value: "-Dconfig.resource=endpoint-application-k8s.conf"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        - name: REQUIRED_CONTACT_POINT_NR
          value: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incidents
  name: incidents
  namespace: incidents
spec:
  replicas: 3
  selector:
    matchLabels:
      app: incidents
  template:
    metadata:
      labels:
        app: incidents
        actorSystemName: incidents
    spec:
      containers:
      - name: incidents
        image: bibilthaysose/incidents
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: management
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /alive
            port: management
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 20
        ports:
        # akka-management and bootstrap
        - name: remoting
          containerPort: 2552
          protocol: TCP
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        - name: JAVA_OPTS
          value: "-Dconfig.resource=cluster-application-k8s.conf"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REQUIRED_CONTACT_POINT_NR
          value: "2"
        - name: CASSANDRA_CONTACT_POINT1
          value: cassandra.incidents.svc.cluster.local

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: incidents
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: incidents
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:incidents:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
